name: C Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y gcc

    - name: Build and Test (Linux)
      run: |
        make
        if [ $? -ne 0 ]; then
          echo "Build failed"
          exit 1
        fi
        ./test_cee
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install mingw --version=8.1.0

    - name: Add MinGW to PATH
      run: echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

    - name: Build (Windows)
      run: |
        make
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Build failed"
          exit 1
        }

    - name: Run Tests (Windows)
      run: |
        .\test_cee.exe
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Tests failed"
          exit 1
        }
